import type { GetStaticProps, NextPage } from 'next'
import Head from 'next/head'

import PageWrapper from '../components/PageWrapper/PageWrapper'
import Cardholder from '../components/Cardholder/Cardholder'
import { Card } from '../models/card.model'
import { getProductData } from '../api/product.api'

interface Props {
    cards: Card[]
}

const Home: NextPage<Props> = ({ cards }) => {
    return (
        <PageWrapper>
            <Head>
                <title>Test task guru group</title>
                <meta name="description" content="Generated by create next app" />
                <link
                    rel="shortcut icon"
                    href={process.env.NEXT_PUBLIC_BASE_PATH + '/favicon.ico'}
                />
            </Head>

            <Cardholder cards={cards} />
        </PageWrapper>
    )
}

export const getStaticProps: GetStaticProps = async () => {
    const cards = await getProductData({ page: 1, limit: 16 })
    return { props: { cards } }
}

export default Home
