import axios from 'axios'
import type { GetStaticProps, NextPage } from 'next'
import Head from 'next/head'

import PageWrapper from '../components/PageWrapper/PageWrapper'
import ProposalCardholder from '../components/ProposalCardholder/ProposalCardholder'
import { Card } from '../models/card.model'

interface Props {
    cards: Card[]
}

const Home: NextPage<Props> = ({ cards }) => {
    return (
        <PageWrapper>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link
                    rel="shortcut icon"
                    href={process.env.NEXT_PUBLIC_BASE_PATH + '/favicon.ico'}
                />
            </Head>

            <ProposalCardholder cards={cards} />
        </PageWrapper>
    )
}

export const getStaticProps: GetStaticProps = async () => {
    const cards = (
        await axios.get('https://6075786f0baf7c0017fa64ce.mockapi.io/products?page=1&limit=16')
    ).data

    return {
        props: { cards }
    }
}

export default Home
